"use client";

// ConnectionModePill — shows LIVE / SIMULATED / OFFLINE clearly.
// This is the trust indicator. It must never be ambiguous.

type Mode = 'LIVE' | 'PROXY' | 'OFFLINE' | null;

interface Props {
  mode: Mode;
  warning?: string;
  size?: 'sm' | 'md';
}

const CONFIG = {
  LIVE: {
    label: 'LIVE',
    dot: '#22d3ee',
    color: '#22d3ee',
    bg: 'rgba(34,211,238,0.08)',
    border: 'rgba(34,211,238,0.28)',
    title: 'You are communicating with the real agent endpoint',
    pulse: true,
  },
  PROXY: {
    label: 'SIMULATED',
    dot: '#a78bfa',
    color: '#a78bfa',
    bg: 'rgba(167,139,250,0.08)',
    border: 'rgba(167,139,250,0.28)',
    title: 'This agent has no live endpoint — responses are generated by AI persona simulation',
    pulse: false,
  },
  OFFLINE: {
    label: 'OFFLINE',
    dot: '#71717a',
    color: '#71717a',
    bg: 'rgba(113,113,122,0.08)',
    border: 'rgba(113,113,122,0.2)',
    title: 'Agent is not responding',
    pulse: false,
  },
} as const;

export default function ConnectionModePill({ mode, warning, size = 'sm' }: Props) {
  if (!mode) return null;
  const cfg = CONFIG[mode];
  const fs = size === 'md' ? 11 : 9;
  const dotSz = size === 'md' ? 6 : 5;

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 3 }}>
      <div
        title={cfg.title}
        style={{
          display: 'inline-flex',
          alignItems: 'center',
          gap: 5,
          padding: size === 'md' ? '3px 9px' : '2px 7px',
          borderRadius: 6,
          background: cfg.bg,
          border: `1px solid ${cfg.border}`,
          cursor: 'help',
        }}
      >
        <div style={{
          width: dotSz,
          height: dotSz,
          borderRadius: '50%',
          background: cfg.dot,
          animation: cfg.pulse ? 'pill-pulse 2s infinite' : 'none',
          flexShrink: 0,
        }} />
        <span style={{
          fontSize: fs,
          fontFamily: "'JetBrains Mono', monospace",
          color: cfg.color,
          fontWeight: 600,
          letterSpacing: '0.1em',
        }}>
          {cfg.label}
        </span>
      </div>

      {warning && (
        <div style={{
          fontSize: 9,
          fontFamily: "'JetBrains Mono', monospace",
          color: '#f59e0b',
          background: 'rgba(245,158,11,0.06)',
          border: '1px solid rgba(245,158,11,0.2)',
          borderRadius: 5,
          padding: '2px 7px',
          maxWidth: 220,
        }}>
          ⚠ {warning}
        </div>
      )}

      <style>{`@keyframes pill-pulse{0%,100%{opacity:1;}50%{opacity:0.4;}}`}</style>
    </div>
  );
}
